env:
  browser: true
  es6: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - '@ridedott/eslint-config'
overrides:
  - files: ./src/**/*spec.ts
    rules:
      '@typescript-eslint/no-magic-numbers': 'off'
  - files: '*.tsx'
    rules:
      '@typescript-eslint/explicit-function-return-type': 'off'
parserOptions:
  ecmaVersion: 10
  project: tsconfig.json
  sourceType: module
rules:
  immutable/no-mutation: 'off'
  immutable/no-this: 'off'
  unicorn/filename-case:
    - error
    - case: kebabCase
