env:
  browser: true
  es6: true
  node: true
extends:
  - '@ridedott/eslint-config'
  - eslint:recommended
  - plugin:react/recommended
overrides:
  - files: ./src/**/*spec.ts
    rules:
      '@typescript-eslint/no-magic-numbers': 'off'
  - files: '*.tsx'
    rules:
      '@typescript-eslint/explicit-function-return-type': 'off'
parserOptions:
  ecmaVersion: 10
  project: tsconfig.json
  sourceType: module
settings:
  react:
    version: detect
rules:
  immutable/no-mutation: 'off'
  immutable/no-this: 'off'
  unicorn/filename-case:
    - error
    - case: kebabCase
  unicorn/prevent-abbreviations:
    - error
    - extendDefaultReplacements: false
  strict-boolean-expressions: 'off'
  eslint-comments/no-use:
    - 'error'
    - allow:
      - eslint-disable-next-line
